HEAD /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

GET /posts HTTP/1.1
Host: jsonplaceholder.typicode.com

###

POST /posts HTTP/1.1
Host: jsonplaceholder.typicode.com
Content-Type: application/json
Content-Length: 88

{
  "title": "Новая публикация",
  "body": "Текст публикации",
  "userId": 31337
}

###

GET http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/offers/68219a44f6dfc46336a5eab9 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/offers HTTP/1.1
Content-Type: application/json

{
  "id": "67ffc9ce848b9b39e7bea172",
  "title": "The Pocket Residence of great views.",
  "description": "An affordable and stylish short-term rental with everything you need for a comfortable city stay.",
  "date": "2025-06-21T08:45:00.000Z",
  "city": "Paris",
  "preview": "photo6.jpg",
  "photos": [
    "photo8.jpg",
    "photo9.jpg",
    "photo10.jpg",
    "photo11.jpg"
  ],
  "isPremium": false,
  "isFavourite": false,
  "rate": 3.7,
  "type": "room",
  "roomsNum": 2,
  "personNum": 3,
  "rent": 94867.01,
  "facilities": [
    "breakfast",
    "air conditioning"
  ],
  "commentsNum": 54,
  "coords": {
    "latitude": 35.6762,
    "longitude": 139.6503
  }
}

###

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarPath": "torrance.png",
  "firstname": "Jack",
  "lastname": "Torrance",
  "password": "shining"
}

###

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}
